# -*- coding: utf-8 -*-
"""untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/gist/Amm22i/b5e99f25ed5b9e7d05baa1039ffe3430/untitled1.ipynb
"""

# @title Default title text



def add (x,y):
  return x+y

def subtract(x, y):
    return x - y

def multiply(x, y):
    return x * y

def divide(x, y):
    if y == 0:
        return "Invalid value for denominator, can't divide by 0!"
    return x / y

def square(x):
    return x ** 2

def power(x, y):
    return x ** y

def sqrt(x):
    if x < 0:
        return "Cannot calculate square root of a negative number."
    return x ** 0.5